# Page settings

baseURL = "/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-137260897-1"






[params]
    #author = "Luke Turcotte"
    #description = "Ottawa-based health services research"


#primaryColor = "#54B689"
primaryColor = "#BF4E30"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Luke Turcotte"
        tagline = "Health Systems Researcher"
        avatar = "avatar2.png"













    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Analytical"
        [[params.skills.list.items]]
        details = "Clinical epidemiology and biostatistics"
        [[params.skills.list.items]]
        details = "SAS & R statistical programming"
        [[params.skills.list.items]]
        details = "Predictive algorithm development"
        [[params.skills.list.items]]
        details = "Explanatory modelling"
        
	[[params.skills.list]]
        title = "Research Interests"
        [[params.skills.list.items]]
        details = "Health information systems"
        [[params.skills.list.items]]
        details = "Multidimensional health assessments"
        [[params.skills.list.items]]
        details = "Post-acute care, long-term care, home care"
        [[params.skills.list.items]]
        details = "Case-mix systems"
        [[params.skills.list.items]]
        details = "Transitions in care "








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Health System Impact Fellowship"
        university = "Canadian Institute for Health Information & University of Waterloo"
        dates = "2019 - 2021"
        [[params.education.list]]
        degree = "PhD in Aging, Health and Well-being"
        university = "University of Waterloo"
        dates = "2014 - 2018"
        [[params.education.list]]
        degree = "MSc in Health Studies and Gerontology"
        university = "University of Waterloo"
        dates = "2012 - 2014"
        [[params.education.list]]
        degree = "BSc in Health Studies and Gerontology"
        university = "University of Waterloo"
        dates = "2008 - 2012"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Luke Turcotte is a health services researcher in the Department of Health Sciences at Brock University. His research is centred around the development and application of health information systems to support clinical decision-making and improve the quality of care for older adults with complex health conditions across the continuum of care."



    [params.experience]
        enable = true

 	 [[params.experience.list]]
        title = "Assistant Professor"
        dates = "2023 - Present"
        company = "Brock University"
        details = "Health services research and evaluation among frail and medically complex older adult patient populations. Masters of Applied Gerontology program core faculty member." 


        [[params.experience.list]]
        title = "Affiliate Investigator"
        dates = "2022 - Present"
        company = "Bruyère Research Institute"
        details = "Health services research for older adults in home care, long-term care, and post-acute care using clinical and administrative health databases."

        [[params.experience.list]]
        title = "Associate Fellow"
        dates = "2021 - Present"
        company = "interRAI"
        details = "Development of multidimensional clinical assessment instruments and decision-support algorithms in collaboration with international researchers and clinicians."

        [[params.experience.list]]
        title = "Adjunct Assistant Professor"
        dates = "2021 - Present"
        company = "University of Waterloo"
        details = "Collaboration with health system experts on research related to quality of care for older adults with complex health conditions across the continuum of care."

         [[params.experience.list]]
        title = "Senior Researcher & Methodologist"
        dates = "2020 - 2022"
        company = "CIHI"
        details = "Development and evaluation of new methodologies to describe the health and well-being of Canadians. Organization-wide methodological support." 



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "COVID-19 in Ontario LTC Homes"
        url = "//covid19ltc.ca"
        tagline = "Dashboard that displays up to date long-term care home COVID-19 outbreak information with facility-level attribute data (e.g., profit status, chain size, design standard, quality of care)."










    [params.information]
        enable = true
	  [[params.information.list]]
	details = "**Turcotte, L. A.**, McArthur, C., Poss, J. W., Heckman, G., Mitchell, L., Morris, J., Foebel, A. D., & Hirdes, J. P. (2023). *Long-Term Care Resident Health and Quality of Care During the COVID-19 Pandemic: A Synthesis Analysis of Canadian Institute for Health Information Data Tables*. Health Services Insights, 16, 11786329231174745. https://doi.org/10.1177/11786329231174745"
        [[params.information.list]]
	details = "**Turcotte, L. A.**, Heckman, G., Rockwood, K., Vetrano, D. L., Hébert, P., McIsaac, D. I., Rhynold, E., Mitchell, L., Mowbray, F. I., Larsen, R. T., & Hirdes, J. P. (2023). *External validation of the hospital frailty risk score among hospitalised home care clients in Canada: A retrospective cohort study*. Age and Ageing, 52(2), afac334. https://doi.org/10.1093/ageing/afac334"
        [[params.information.list.items]]
        details = "**Turcotte, L. A.**, Zalucky, A. A., Stall, N. M., Downar, J., Rockwood, K., Theou, O., McArthur, C., & Heckman, G. (2021). *Baseline Frailty as a Predictor of Survival After Critical Care: A Retrospective Cohort Study of Older Adults Receiving Home Care in Ontario, Canada*. Chest, 160(6), 2101–2111. https://doi.org/10.1016/j.chest.2021.06.009"
        [[params.information.list.items]]
        details = "**Turcotte, L. A.**, Daniel, I., & Hirdes, J. P. (2020). *The Post-Acute Delayed Discharge Risk Scale: Derivation and Validation With Ontario Alternate Level of Care Patients in Ontario Complex Continuing Care Hospitals*. Journal of the American Medical Directors Association, 21(4), 538–544.e1. https://doi.org/10.1016/j.jamda.2019.12.022"
	[[params.information.list.items]]
	details = "**Turcotte, L. A.**, Poss, J., Fries, B., & Hirdes, J. P. (2019). *An Overview of International Staff Time Measurement Validation Studies of the RUG-III Case-mix System*. Health services insights, 12, 1178632919827926. https://doi.org/10.1177/1178632919827"
        [[params.information.list.items]]
        details = "Visit [PubMed](https://pubmed.ncbi.nlm.nih.gov/?term=luke+turcotte&sort=date) for all publications"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/luketurcotte"
        title = "@luketurcotte"


[params.footer]
    copyright = "Luke Turcotte"


